--CREATE DATABASE Formulario
USE Formulario

CREATE TABLE Usuario (
IDUser INT IDENTITY(1,1) PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
Usuario VARCHAR(20) NOT NULL UNIQUE,
Senha VARCHAR(10) NOT NULL,
CEP VARCHAR(8) NOT NULL,
NumeroCasa VARCHAR(6) NOT NULL,
Cidade VARCHAR(40) NOT NULL,
UF VARCHAR(2) NOT NULL,
Email VARCHAR(50) NOT NULL UNIQUE,
Telefone1 VARCHAR(12) NOT NULL,
Telefone2 VARCHAR(12) NULL
)