CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [Nome] VARCHAR(50) NOT NULL,
	[Usuario] VARCHAR(20) NOT NULL,
	[Senha] VARCHAR(10) NOT NULL,
	[CEP] VARCHAR(9) NOT NULL,
	[Cidade] VARCHAR(35) NOT NULL,
	[UF] VARCHAR(2) NOT NULL,
	[Email] VARCHAR(40) NOT NULL,
	[Telefone1] VARCHAR(12) NOT NULL,
	[Telefone2] VARCHAR(12) NULL
)
